### ISSUE TITLE
Cant Debug Please Help 

### ISSUE THREAD

**Issue by muratoznn** [abhijeet2096/TL-WN722N-V2#35]
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' all...........................(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.0-kali1-amd64 (x86_64)
Consult /var/lib/dkms/8188eu/1.2/build/make.log for more information.

/usr/src/linux-headers-4.19.0-kali1-common/include/linux/ieee80211.h:1442: note: this is the location of the previous definition
 #define IEEE80211_MAX_AMPDU_BUF  0x100

/var/lib/dkms/8188eu/1.2/build/os_dep/linux/os_intfs.c:751:22: error: initialization of ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_de$
  .ndo_select_queue = rtw_select_queue,
                      ^~~~~~~~~~~~~~~~
/var/lib/dkms/8188eu/1.2/build/os_dep/linux/os_intfs.c:751:22: note: (near initialization for ‘rtw_netdev_ops.ndo_select_queue’)
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-4.19.0-kali1-common/scripts/Makefile.build:309: /var/lib/dkms/8188eu/1.2/build/os_dep/linux/os_intfs.o] Error 1
make[3]: *** [/usr/src/linux-headers-4.19.0-kali1-common/Makefile:1532: _module_/var/lib/dkms/8188eu/1.2/build] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-kali1-amd64'
make: *** [Makefile:1365: modules] Error 2
